### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [samvv/js-proxy-deep#2]
Hello,

Thank you for this very useful package. I just wanted to warn you that the npm package contains the version `1.0.1` and is buggy (the set handler does not pass the value which makes it unusable). Although, it seems to be fixed in the version `1.2.0`. Could you update the npm repository ?.

Thank you very much

**Comment by samvv** [comment]
See #4 for details.

**Comment by samvv** [comment]
Should be all good now.
