### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [samvv/js-proxy-deep#4]
Thank you again for your pacakge.

It seems that the README.md is not in sync with the latests version of the code base. Indeed, in `get` handlers I get 4 arguments and the readme says there should be only two. It seems you are passing the recieved, but I don't feel confident enough to update the Readme myself and make a pull request.

Thank you for your help

**Comment by samvv** [comment]
Hi Guillaume,

Thanks for the feedback. Coincidentally, I'm just now writing a package which will require this package. I'll prepare a new version later this day and update it to the registry. Don't worry about the README. I'll fix it while I'm on it.

Regards,
Sam
